version: '3'
services:
  db:
    container_name: laravel_test_db
    build: ./db/
    image: laravel_test_db
    environment:
      MYSQL_ROOT_PASSWORD: Password@1234
      MYSQL_DATABASE: laravel_db
    ports:
      - 13306:3306
  app:
    container_name: laravel_test_app
    build: ./app/
    image: laravel_test_app
    ports:
      - 8080:8000
    links:
      - db
    volumes:
      - ../laravel:/var/www/html/laravel
    stdin_open: true
    tty: true
    depends_on:
      - db
